#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 42
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_DOT = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_BQUOTE = 10,
  anon_sym_COMMA = 11,
  anon_sym_COMMA_AT = 12,
  anon_sym_POUNDu8_LPAREN = 13,
  sym_number = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  sym_escape_sequence = 17,
  sym_keyword = 18,
  sym_boolean = 19,
  sym_character = 20,
  sym_comment = 21,
  sym_block_comment = 22,
  sym_source_file = 23,
  sym__form = 24,
  sym_list = 25,
  sym_vector = 26,
  sym_hash_map = 27,
  sym_quote = 28,
  sym_quasiquote = 29,
  sym_unquote = 30,
  sym_unquote_splicing = 31,
  sym_byte_vector = 32,
  sym__atom = 33,
  sym_string = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_byte_vector_repeat1 = 36,
  aux_sym_string_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_COMMA_AT] = ",@",
  [anon_sym_POUNDu8_LPAREN] = "#u8(",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_keyword] = "keyword",
  [sym_boolean] = "boolean",
  [sym_character] = "character",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__form] = "_form",
  [sym_list] = "list",
  [sym_vector] = "vector",
  [sym_hash_map] = "hash_map",
  [sym_quote] = "quote",
  [sym_quasiquote] = "quasiquote",
  [sym_unquote] = "unquote",
  [sym_unquote_splicing] = "unquote_splicing",
  [sym_byte_vector] = "byte_vector",
  [sym__atom] = "_atom",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_byte_vector_repeat1] = "byte_vector_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COMMA_AT] = anon_sym_COMMA_AT,
  [anon_sym_POUNDu8_LPAREN] = anon_sym_POUNDu8_LPAREN,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_keyword] = sym_keyword,
  [sym_boolean] = sym_boolean,
  [sym_character] = sym_character,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__form] = sym__form,
  [sym_list] = sym_list,
  [sym_vector] = sym_vector,
  [sym_hash_map] = sym_hash_map,
  [sym_quote] = sym_quote,
  [sym_quasiquote] = sym_quasiquote,
  [sym_unquote] = sym_unquote,
  [sym_unquote_splicing] = sym_unquote_splicing,
  [sym_byte_vector] = sym_byte_vector,
  [sym__atom] = sym__atom,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_byte_vector_repeat1] = aux_sym_byte_vector_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDu8_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_map] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quasiquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote_splicing] = {
    .visible = true,
    .named = true,
  },
  [sym_byte_vector] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_byte_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 7,
  [12] = 12,
  [13] = 12,
  [14] = 9,
  [15] = 6,
  [16] = 10,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 17,
  [24] = 24,
  [25] = 22,
  [26] = 24,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 35,
  [43] = 34,
  [44] = 37,
  [45] = 38,
  [46] = 39,
  [47] = 29,
  [48] = 32,
  [49] = 33,
  [50] = 30,
  [51] = 31,
  [52] = 40,
  [53] = 41,
  [54] = 36,
  [55] = 27,
  [56] = 28,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 59,
  [61] = 58,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 64,
  [67] = 67,
  [68] = 68,
  [69] = 67,
};

static TSCharacterRange sym_symbol_character_set_2[] = {
  {'!', '!'}, {'%', '&'}, {'*', '+'}, {'-', '9'}, {'<', '?'}, {'A', 'Z'}, {'^', '_'}, {'a', 'z'},
  {'~', '~'}, {0xc0, 0x24f},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 53,
        '#', 7,
        '\'', 44,
        '(', 37,
        ')', 38,
        ',', 46,
        '-', 64,
        '.', 39,
        ':', 33,
        ';', 74,
        '[', 40,
        '\\', 6,
        ']', 41,
        '`', 45,
        'f', 58,
        't', 61,
        '{', 42,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'z') ||
          lookahead == '~' ||
          (0xc0 <= lookahead && lookahead <= 0x24f)) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == ';') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(38);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == '8') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        'U', 32,
        'u', 28,
        'x', 25,
        '"', 57,
        '0', 57,
        '\\', 57,
        'n', 57,
        'r', 57,
        't', 57,
      );
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(4);
      if (lookahead == 'f' ||
          lookahead == 't') ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(69);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(71);
      if (lookahead == 'r') ADVANCE(72);
      if (lookahead == 's') ADVANCE(73);
      if (lookahead == 't') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'w') ADVANCE(14);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 33:
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 53,
        '#', 7,
        '\'', 44,
        '(', 37,
        ')', 38,
        ',', 46,
        '-', 64,
        '.', 39,
        ':', 33,
        ';', 74,
        '[', 40,
        ']', 41,
        '`', 45,
        'f', 58,
        't', 61,
        '{', 42,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= 'z') ||
          lookahead == '~' ||
          (0xc0 <= lookahead && lookahead <= 0x24f)) ADVANCE(66);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 53,
        '#', 7,
        '\'', 44,
        '(', 37,
        ')', 38,
        ',', 46,
        '-', 64,
        ':', 33,
        ';', 74,
        '[', 40,
        ']', 41,
        '`', 45,
        'f', 58,
        't', 61,
        '{', 42,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= 'z') ||
          lookahead == '~' ||
          (0xc0 <= lookahead && lookahead <= 0x24f)) ADVANCE(66);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '@') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA_AT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_POUNDu8_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(74);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'a') ADVANCE(60);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(68);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(62);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'r') ADVANCE(63);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 's') ADVANCE(59);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'u') ADVANCE(59);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_keyword);
      if (set_contains(sym_symbol_character_set_2, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 35, .external_lex_state = 1},
  [2] = {.lex_state = 35, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 35, .external_lex_state = 1},
  [7] = {.lex_state = 35, .external_lex_state = 1},
  [8] = {.lex_state = 35, .external_lex_state = 1},
  [9] = {.lex_state = 35, .external_lex_state = 1},
  [10] = {.lex_state = 35, .external_lex_state = 1},
  [11] = {.lex_state = 35, .external_lex_state = 1},
  [12] = {.lex_state = 35, .external_lex_state = 1},
  [13] = {.lex_state = 35, .external_lex_state = 1},
  [14] = {.lex_state = 35, .external_lex_state = 1},
  [15] = {.lex_state = 35, .external_lex_state = 1},
  [16] = {.lex_state = 35, .external_lex_state = 1},
  [17] = {.lex_state = 35, .external_lex_state = 1},
  [18] = {.lex_state = 35, .external_lex_state = 1},
  [19] = {.lex_state = 35, .external_lex_state = 1},
  [20] = {.lex_state = 35, .external_lex_state = 1},
  [21] = {.lex_state = 35, .external_lex_state = 1},
  [22] = {.lex_state = 35, .external_lex_state = 1},
  [23] = {.lex_state = 35, .external_lex_state = 1},
  [24] = {.lex_state = 35, .external_lex_state = 1},
  [25] = {.lex_state = 35, .external_lex_state = 1},
  [26] = {.lex_state = 35, .external_lex_state = 1},
  [27] = {.lex_state = 35, .external_lex_state = 1},
  [28] = {.lex_state = 35, .external_lex_state = 1},
  [29] = {.lex_state = 35, .external_lex_state = 1},
  [30] = {.lex_state = 35, .external_lex_state = 1},
  [31] = {.lex_state = 35, .external_lex_state = 1},
  [32] = {.lex_state = 35, .external_lex_state = 1},
  [33] = {.lex_state = 35, .external_lex_state = 1},
  [34] = {.lex_state = 35, .external_lex_state = 1},
  [35] = {.lex_state = 35, .external_lex_state = 1},
  [36] = {.lex_state = 35, .external_lex_state = 1},
  [37] = {.lex_state = 35, .external_lex_state = 1},
  [38] = {.lex_state = 35, .external_lex_state = 1},
  [39] = {.lex_state = 35, .external_lex_state = 1},
  [40] = {.lex_state = 35, .external_lex_state = 1},
  [41] = {.lex_state = 35, .external_lex_state = 1},
  [42] = {.lex_state = 0, .external_lex_state = 1},
  [43] = {.lex_state = 0, .external_lex_state = 1},
  [44] = {.lex_state = 0, .external_lex_state = 1},
  [45] = {.lex_state = 0, .external_lex_state = 1},
  [46] = {.lex_state = 0, .external_lex_state = 1},
  [47] = {.lex_state = 0, .external_lex_state = 1},
  [48] = {.lex_state = 0, .external_lex_state = 1},
  [49] = {.lex_state = 0, .external_lex_state = 1},
  [50] = {.lex_state = 0, .external_lex_state = 1},
  [51] = {.lex_state = 0, .external_lex_state = 1},
  [52] = {.lex_state = 0, .external_lex_state = 1},
  [53] = {.lex_state = 0, .external_lex_state = 1},
  [54] = {.lex_state = 0, .external_lex_state = 1},
  [55] = {.lex_state = 0, .external_lex_state = 1},
  [56] = {.lex_state = 0, .external_lex_state = 1},
  [57] = {.lex_state = 1, .external_lex_state = 1},
  [58] = {.lex_state = 1, .external_lex_state = 1},
  [59] = {.lex_state = 1, .external_lex_state = 1},
  [60] = {.lex_state = 1, .external_lex_state = 1},
  [61] = {.lex_state = 1, .external_lex_state = 1},
  [62] = {.lex_state = 3, .external_lex_state = 1},
  [63] = {.lex_state = 3, .external_lex_state = 1},
  [64] = {.lex_state = 3, .external_lex_state = 1},
  [65] = {.lex_state = 3, .external_lex_state = 1},
  [66] = {.lex_state = 3, .external_lex_state = 1},
  [67] = {.lex_state = 0, .external_lex_state = 1},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COMMA_AT] = ACTIONS(1),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_character] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(68),
    [sym__form] = STATE(8),
    [sym_list] = STATE(8),
    [sym_vector] = STATE(8),
    [sym_hash_map] = STATE(8),
    [sym_quote] = STATE(8),
    [sym_quasiquote] = STATE(8),
    [sym_unquote] = STATE(8),
    [sym_unquote_splicing] = STATE(8),
    [sym_byte_vector] = STATE(8),
    [sym__atom] = STATE(8),
    [sym_string] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_symbol] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(27),
    [sym_boolean] = ACTIONS(27),
    [sym_character] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_symbol] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(34),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(40),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(46),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_COMMA_AT] = ACTIONS(52),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(55),
    [sym_number] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(58),
    [sym_keyword] = ACTIONS(61),
    [sym_boolean] = ACTIONS(61),
    [sym_character] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__form] = STATE(4),
    [sym_list] = STATE(4),
    [sym_vector] = STATE(4),
    [sym_hash_map] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_quasiquote] = STATE(4),
    [sym_unquote] = STATE(4),
    [sym_unquote_splicing] = STATE(4),
    [sym_byte_vector] = STATE(4),
    [sym__atom] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_symbol] = ACTIONS(64),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_DOT] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(88),
    [sym_boolean] = ACTIONS(88),
    [sym_character] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__form] = STATE(4),
    [sym_list] = STATE(4),
    [sym_vector] = STATE(4),
    [sym_hash_map] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_quasiquote] = STATE(4),
    [sym_unquote] = STATE(4),
    [sym_unquote_splicing] = STATE(4),
    [sym_byte_vector] = STATE(4),
    [sym__atom] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_symbol] = ACTIONS(90),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_DOT] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_SQUOTE] = ACTIONS(104),
    [anon_sym_BQUOTE] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_COMMA_AT] = ACTIONS(113),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(116),
    [sym_number] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(119),
    [sym_keyword] = ACTIONS(122),
    [sym_boolean] = ACTIONS(122),
    [sym_character] = ACTIONS(122),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__form] = STATE(4),
    [sym_list] = STATE(4),
    [sym_vector] = STATE(4),
    [sym_hash_map] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_quasiquote] = STATE(4),
    [sym_unquote] = STATE(4),
    [sym_unquote_splicing] = STATE(4),
    [sym_byte_vector] = STATE(4),
    [sym__atom] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_symbol] = ACTIONS(64),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_DOT] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(88),
    [sym_boolean] = ACTIONS(88),
    [sym_character] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [6] = {
    [sym__form] = STATE(11),
    [sym_list] = STATE(11),
    [sym_vector] = STATE(11),
    [sym_hash_map] = STATE(11),
    [sym_quote] = STATE(11),
    [sym_quasiquote] = STATE(11),
    [sym_unquote] = STATE(11),
    [sym_unquote_splicing] = STATE(11),
    [sym_byte_vector] = STATE(11),
    [sym__atom] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(131),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(129),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(133),
    [sym_boolean] = ACTIONS(133),
    [sym_character] = ACTIONS(133),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [7] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(137),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(139),
    [sym_boolean] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [8] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(141),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(139),
    [sym_boolean] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [9] = {
    [sym__form] = STATE(10),
    [sym_list] = STATE(10),
    [sym_vector] = STATE(10),
    [sym_hash_map] = STATE(10),
    [sym_quote] = STATE(10),
    [sym_quasiquote] = STATE(10),
    [sym_unquote] = STATE(10),
    [sym_unquote_splicing] = STATE(10),
    [sym_byte_vector] = STATE(10),
    [sym__atom] = STATE(10),
    [sym_string] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_symbol] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(145),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(147),
    [sym_boolean] = ACTIONS(147),
    [sym_character] = ACTIONS(147),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [10] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(149),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(139),
    [sym_boolean] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [11] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(151),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(139),
    [sym_boolean] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [12] = {
    [sym__form] = STATE(3),
    [sym_list] = STATE(3),
    [sym_vector] = STATE(3),
    [sym_hash_map] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_quasiquote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_unquote_splicing] = STATE(3),
    [sym_byte_vector] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_symbol] = ACTIONS(153),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(153),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(157),
    [sym_boolean] = ACTIONS(157),
    [sym_character] = ACTIONS(157),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [13] = {
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_vector] = STATE(5),
    [sym_hash_map] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_quasiquote] = STATE(5),
    [sym_unquote] = STATE(5),
    [sym_unquote_splicing] = STATE(5),
    [sym_byte_vector] = STATE(5),
    [sym__atom] = STATE(5),
    [sym_string] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(159),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(163),
    [sym_boolean] = ACTIONS(163),
    [sym_character] = ACTIONS(163),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [14] = {
    [sym__form] = STATE(16),
    [sym_list] = STATE(16),
    [sym_vector] = STATE(16),
    [sym_hash_map] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_quasiquote] = STATE(16),
    [sym_unquote] = STATE(16),
    [sym_unquote_splicing] = STATE(16),
    [sym_byte_vector] = STATE(16),
    [sym__atom] = STATE(16),
    [sym_string] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_symbol] = ACTIONS(165),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(165),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(169),
    [sym_boolean] = ACTIONS(169),
    [sym_character] = ACTIONS(169),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [15] = {
    [sym__form] = STATE(7),
    [sym_list] = STATE(7),
    [sym_vector] = STATE(7),
    [sym_hash_map] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_quasiquote] = STATE(7),
    [sym_unquote] = STATE(7),
    [sym_unquote_splicing] = STATE(7),
    [sym_byte_vector] = STATE(7),
    [sym__atom] = STATE(7),
    [sym_string] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_symbol] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(173),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(171),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(175),
    [sym_boolean] = ACTIONS(175),
    [sym_character] = ACTIONS(175),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [16] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_hash_map] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_byte_vector] = STATE(2),
    [sym__atom] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(177),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(139),
    [sym_boolean] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [17] = {
    [sym__form] = STATE(34),
    [sym_list] = STATE(34),
    [sym_vector] = STATE(34),
    [sym_hash_map] = STATE(34),
    [sym_quote] = STATE(34),
    [sym_quasiquote] = STATE(34),
    [sym_unquote] = STATE(34),
    [sym_unquote_splicing] = STATE(34),
    [sym_byte_vector] = STATE(34),
    [sym__atom] = STATE(34),
    [sym_string] = STATE(34),
    [sym_symbol] = ACTIONS(179),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(179),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(181),
    [sym_boolean] = ACTIONS(181),
    [sym_character] = ACTIONS(181),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [18] = {
    [sym__form] = STATE(69),
    [sym_list] = STATE(69),
    [sym_vector] = STATE(69),
    [sym_hash_map] = STATE(69),
    [sym_quote] = STATE(69),
    [sym_quasiquote] = STATE(69),
    [sym_unquote] = STATE(69),
    [sym_unquote_splicing] = STATE(69),
    [sym_byte_vector] = STATE(69),
    [sym__atom] = STATE(69),
    [sym_string] = STATE(69),
    [sym_symbol] = ACTIONS(183),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(183),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(185),
    [sym_boolean] = ACTIONS(185),
    [sym_character] = ACTIONS(185),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [19] = {
    [sym__form] = STATE(67),
    [sym_list] = STATE(67),
    [sym_vector] = STATE(67),
    [sym_hash_map] = STATE(67),
    [sym_quote] = STATE(67),
    [sym_quasiquote] = STATE(67),
    [sym_unquote] = STATE(67),
    [sym_unquote_splicing] = STATE(67),
    [sym_byte_vector] = STATE(67),
    [sym__atom] = STATE(67),
    [sym_string] = STATE(67),
    [sym_symbol] = ACTIONS(187),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(187),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(189),
    [sym_boolean] = ACTIONS(189),
    [sym_character] = ACTIONS(189),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [20] = {
    [sym__form] = STATE(27),
    [sym_list] = STATE(27),
    [sym_vector] = STATE(27),
    [sym_hash_map] = STATE(27),
    [sym_quote] = STATE(27),
    [sym_quasiquote] = STATE(27),
    [sym_unquote] = STATE(27),
    [sym_unquote_splicing] = STATE(27),
    [sym_byte_vector] = STATE(27),
    [sym__atom] = STATE(27),
    [sym_string] = STATE(27),
    [sym_symbol] = ACTIONS(191),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(191),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(193),
    [sym_boolean] = ACTIONS(193),
    [sym_character] = ACTIONS(193),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [21] = {
    [sym__form] = STATE(55),
    [sym_list] = STATE(55),
    [sym_vector] = STATE(55),
    [sym_hash_map] = STATE(55),
    [sym_quote] = STATE(55),
    [sym_quasiquote] = STATE(55),
    [sym_unquote] = STATE(55),
    [sym_unquote_splicing] = STATE(55),
    [sym_byte_vector] = STATE(55),
    [sym__atom] = STATE(55),
    [sym_string] = STATE(55),
    [sym_symbol] = ACTIONS(195),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(195),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(197),
    [sym_boolean] = ACTIONS(197),
    [sym_character] = ACTIONS(197),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [22] = {
    [sym__form] = STATE(56),
    [sym_list] = STATE(56),
    [sym_vector] = STATE(56),
    [sym_hash_map] = STATE(56),
    [sym_quote] = STATE(56),
    [sym_quasiquote] = STATE(56),
    [sym_unquote] = STATE(56),
    [sym_unquote_splicing] = STATE(56),
    [sym_byte_vector] = STATE(56),
    [sym__atom] = STATE(56),
    [sym_string] = STATE(56),
    [sym_symbol] = ACTIONS(199),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(199),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(201),
    [sym_boolean] = ACTIONS(201),
    [sym_character] = ACTIONS(201),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [23] = {
    [sym__form] = STATE(43),
    [sym_list] = STATE(43),
    [sym_vector] = STATE(43),
    [sym_hash_map] = STATE(43),
    [sym_quote] = STATE(43),
    [sym_quasiquote] = STATE(43),
    [sym_unquote] = STATE(43),
    [sym_unquote_splicing] = STATE(43),
    [sym_byte_vector] = STATE(43),
    [sym__atom] = STATE(43),
    [sym_string] = STATE(43),
    [sym_symbol] = ACTIONS(203),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(203),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(205),
    [sym_boolean] = ACTIONS(205),
    [sym_character] = ACTIONS(205),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [24] = {
    [sym__form] = STATE(44),
    [sym_list] = STATE(44),
    [sym_vector] = STATE(44),
    [sym_hash_map] = STATE(44),
    [sym_quote] = STATE(44),
    [sym_quasiquote] = STATE(44),
    [sym_unquote] = STATE(44),
    [sym_unquote_splicing] = STATE(44),
    [sym_byte_vector] = STATE(44),
    [sym__atom] = STATE(44),
    [sym_string] = STATE(44),
    [sym_symbol] = ACTIONS(207),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_BQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_COMMA_AT] = ACTIONS(82),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(84),
    [sym_number] = ACTIONS(207),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_keyword] = ACTIONS(209),
    [sym_boolean] = ACTIONS(209),
    [sym_character] = ACTIONS(209),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [25] = {
    [sym__form] = STATE(28),
    [sym_list] = STATE(28),
    [sym_vector] = STATE(28),
    [sym_hash_map] = STATE(28),
    [sym_quote] = STATE(28),
    [sym_quasiquote] = STATE(28),
    [sym_unquote] = STATE(28),
    [sym_unquote_splicing] = STATE(28),
    [sym_byte_vector] = STATE(28),
    [sym__atom] = STATE(28),
    [sym_string] = STATE(28),
    [sym_symbol] = ACTIONS(211),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(211),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(213),
    [sym_boolean] = ACTIONS(213),
    [sym_character] = ACTIONS(213),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [26] = {
    [sym__form] = STATE(37),
    [sym_list] = STATE(37),
    [sym_vector] = STATE(37),
    [sym_hash_map] = STATE(37),
    [sym_quote] = STATE(37),
    [sym_quasiquote] = STATE(37),
    [sym_unquote] = STATE(37),
    [sym_unquote_splicing] = STATE(37),
    [sym_byte_vector] = STATE(37),
    [sym__atom] = STATE(37),
    [sym_string] = STATE(37),
    [sym_symbol] = ACTIONS(215),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(23),
    [sym_number] = ACTIONS(215),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_keyword] = ACTIONS(217),
    [sym_boolean] = ACTIONS(217),
    [sym_character] = ACTIONS(217),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [27] = {
    [ts_builtin_sym_end] = ACTIONS(219),
    [sym_symbol] = ACTIONS(221),
    [anon_sym_LPAREN] = ACTIONS(219),
    [anon_sym_RPAREN] = ACTIONS(219),
    [anon_sym_LBRACK] = ACTIONS(219),
    [anon_sym_RBRACK] = ACTIONS(219),
    [anon_sym_LBRACE] = ACTIONS(219),
    [anon_sym_RBRACE] = ACTIONS(219),
    [anon_sym_SQUOTE] = ACTIONS(219),
    [anon_sym_BQUOTE] = ACTIONS(219),
    [anon_sym_COMMA] = ACTIONS(221),
    [anon_sym_COMMA_AT] = ACTIONS(219),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(219),
    [sym_number] = ACTIONS(221),
    [anon_sym_DQUOTE] = ACTIONS(219),
    [sym_keyword] = ACTIONS(219),
    [sym_boolean] = ACTIONS(219),
    [sym_character] = ACTIONS(219),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [28] = {
    [ts_builtin_sym_end] = ACTIONS(223),
    [sym_symbol] = ACTIONS(225),
    [anon_sym_LPAREN] = ACTIONS(223),
    [anon_sym_RPAREN] = ACTIONS(223),
    [anon_sym_LBRACK] = ACTIONS(223),
    [anon_sym_RBRACK] = ACTIONS(223),
    [anon_sym_LBRACE] = ACTIONS(223),
    [anon_sym_RBRACE] = ACTIONS(223),
    [anon_sym_SQUOTE] = ACTIONS(223),
    [anon_sym_BQUOTE] = ACTIONS(223),
    [anon_sym_COMMA] = ACTIONS(225),
    [anon_sym_COMMA_AT] = ACTIONS(223),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(223),
    [sym_number] = ACTIONS(225),
    [anon_sym_DQUOTE] = ACTIONS(223),
    [sym_keyword] = ACTIONS(223),
    [sym_boolean] = ACTIONS(223),
    [sym_character] = ACTIONS(223),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [29] = {
    [ts_builtin_sym_end] = ACTIONS(227),
    [sym_symbol] = ACTIONS(229),
    [anon_sym_LPAREN] = ACTIONS(227),
    [anon_sym_RPAREN] = ACTIONS(227),
    [anon_sym_LBRACK] = ACTIONS(227),
    [anon_sym_RBRACK] = ACTIONS(227),
    [anon_sym_LBRACE] = ACTIONS(227),
    [anon_sym_RBRACE] = ACTIONS(227),
    [anon_sym_SQUOTE] = ACTIONS(227),
    [anon_sym_BQUOTE] = ACTIONS(227),
    [anon_sym_COMMA] = ACTIONS(229),
    [anon_sym_COMMA_AT] = ACTIONS(227),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(227),
    [sym_number] = ACTIONS(229),
    [anon_sym_DQUOTE] = ACTIONS(227),
    [sym_keyword] = ACTIONS(227),
    [sym_boolean] = ACTIONS(227),
    [sym_character] = ACTIONS(227),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [30] = {
    [ts_builtin_sym_end] = ACTIONS(231),
    [sym_symbol] = ACTIONS(233),
    [anon_sym_LPAREN] = ACTIONS(231),
    [anon_sym_RPAREN] = ACTIONS(231),
    [anon_sym_LBRACK] = ACTIONS(231),
    [anon_sym_RBRACK] = ACTIONS(231),
    [anon_sym_LBRACE] = ACTIONS(231),
    [anon_sym_RBRACE] = ACTIONS(231),
    [anon_sym_SQUOTE] = ACTIONS(231),
    [anon_sym_BQUOTE] = ACTIONS(231),
    [anon_sym_COMMA] = ACTIONS(233),
    [anon_sym_COMMA_AT] = ACTIONS(231),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(231),
    [sym_number] = ACTIONS(233),
    [anon_sym_DQUOTE] = ACTIONS(231),
    [sym_keyword] = ACTIONS(231),
    [sym_boolean] = ACTIONS(231),
    [sym_character] = ACTIONS(231),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [31] = {
    [ts_builtin_sym_end] = ACTIONS(235),
    [sym_symbol] = ACTIONS(237),
    [anon_sym_LPAREN] = ACTIONS(235),
    [anon_sym_RPAREN] = ACTIONS(235),
    [anon_sym_LBRACK] = ACTIONS(235),
    [anon_sym_RBRACK] = ACTIONS(235),
    [anon_sym_LBRACE] = ACTIONS(235),
    [anon_sym_RBRACE] = ACTIONS(235),
    [anon_sym_SQUOTE] = ACTIONS(235),
    [anon_sym_BQUOTE] = ACTIONS(235),
    [anon_sym_COMMA] = ACTIONS(237),
    [anon_sym_COMMA_AT] = ACTIONS(235),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(235),
    [sym_number] = ACTIONS(237),
    [anon_sym_DQUOTE] = ACTIONS(235),
    [sym_keyword] = ACTIONS(235),
    [sym_boolean] = ACTIONS(235),
    [sym_character] = ACTIONS(235),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [32] = {
    [ts_builtin_sym_end] = ACTIONS(239),
    [sym_symbol] = ACTIONS(241),
    [anon_sym_LPAREN] = ACTIONS(239),
    [anon_sym_RPAREN] = ACTIONS(239),
    [anon_sym_LBRACK] = ACTIONS(239),
    [anon_sym_RBRACK] = ACTIONS(239),
    [anon_sym_LBRACE] = ACTIONS(239),
    [anon_sym_RBRACE] = ACTIONS(239),
    [anon_sym_SQUOTE] = ACTIONS(239),
    [anon_sym_BQUOTE] = ACTIONS(239),
    [anon_sym_COMMA] = ACTIONS(241),
    [anon_sym_COMMA_AT] = ACTIONS(239),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(239),
    [sym_number] = ACTIONS(241),
    [anon_sym_DQUOTE] = ACTIONS(239),
    [sym_keyword] = ACTIONS(239),
    [sym_boolean] = ACTIONS(239),
    [sym_character] = ACTIONS(239),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [33] = {
    [ts_builtin_sym_end] = ACTIONS(243),
    [sym_symbol] = ACTIONS(245),
    [anon_sym_LPAREN] = ACTIONS(243),
    [anon_sym_RPAREN] = ACTIONS(243),
    [anon_sym_LBRACK] = ACTIONS(243),
    [anon_sym_RBRACK] = ACTIONS(243),
    [anon_sym_LBRACE] = ACTIONS(243),
    [anon_sym_RBRACE] = ACTIONS(243),
    [anon_sym_SQUOTE] = ACTIONS(243),
    [anon_sym_BQUOTE] = ACTIONS(243),
    [anon_sym_COMMA] = ACTIONS(245),
    [anon_sym_COMMA_AT] = ACTIONS(243),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(243),
    [sym_number] = ACTIONS(245),
    [anon_sym_DQUOTE] = ACTIONS(243),
    [sym_keyword] = ACTIONS(243),
    [sym_boolean] = ACTIONS(243),
    [sym_character] = ACTIONS(243),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [34] = {
    [ts_builtin_sym_end] = ACTIONS(247),
    [sym_symbol] = ACTIONS(249),
    [anon_sym_LPAREN] = ACTIONS(247),
    [anon_sym_RPAREN] = ACTIONS(247),
    [anon_sym_LBRACK] = ACTIONS(247),
    [anon_sym_RBRACK] = ACTIONS(247),
    [anon_sym_LBRACE] = ACTIONS(247),
    [anon_sym_RBRACE] = ACTIONS(247),
    [anon_sym_SQUOTE] = ACTIONS(247),
    [anon_sym_BQUOTE] = ACTIONS(247),
    [anon_sym_COMMA] = ACTIONS(249),
    [anon_sym_COMMA_AT] = ACTIONS(247),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(247),
    [sym_number] = ACTIONS(249),
    [anon_sym_DQUOTE] = ACTIONS(247),
    [sym_keyword] = ACTIONS(247),
    [sym_boolean] = ACTIONS(247),
    [sym_character] = ACTIONS(247),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [35] = {
    [ts_builtin_sym_end] = ACTIONS(251),
    [sym_symbol] = ACTIONS(253),
    [anon_sym_LPAREN] = ACTIONS(251),
    [anon_sym_RPAREN] = ACTIONS(251),
    [anon_sym_LBRACK] = ACTIONS(251),
    [anon_sym_RBRACK] = ACTIONS(251),
    [anon_sym_LBRACE] = ACTIONS(251),
    [anon_sym_RBRACE] = ACTIONS(251),
    [anon_sym_SQUOTE] = ACTIONS(251),
    [anon_sym_BQUOTE] = ACTIONS(251),
    [anon_sym_COMMA] = ACTIONS(253),
    [anon_sym_COMMA_AT] = ACTIONS(251),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(251),
    [sym_number] = ACTIONS(253),
    [anon_sym_DQUOTE] = ACTIONS(251),
    [sym_keyword] = ACTIONS(251),
    [sym_boolean] = ACTIONS(251),
    [sym_character] = ACTIONS(251),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [36] = {
    [ts_builtin_sym_end] = ACTIONS(255),
    [sym_symbol] = ACTIONS(257),
    [anon_sym_LPAREN] = ACTIONS(255),
    [anon_sym_RPAREN] = ACTIONS(255),
    [anon_sym_LBRACK] = ACTIONS(255),
    [anon_sym_RBRACK] = ACTIONS(255),
    [anon_sym_LBRACE] = ACTIONS(255),
    [anon_sym_RBRACE] = ACTIONS(255),
    [anon_sym_SQUOTE] = ACTIONS(255),
    [anon_sym_BQUOTE] = ACTIONS(255),
    [anon_sym_COMMA] = ACTIONS(257),
    [anon_sym_COMMA_AT] = ACTIONS(255),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(255),
    [sym_number] = ACTIONS(257),
    [anon_sym_DQUOTE] = ACTIONS(255),
    [sym_keyword] = ACTIONS(255),
    [sym_boolean] = ACTIONS(255),
    [sym_character] = ACTIONS(255),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [37] = {
    [ts_builtin_sym_end] = ACTIONS(259),
    [sym_symbol] = ACTIONS(261),
    [anon_sym_LPAREN] = ACTIONS(259),
    [anon_sym_RPAREN] = ACTIONS(259),
    [anon_sym_LBRACK] = ACTIONS(259),
    [anon_sym_RBRACK] = ACTIONS(259),
    [anon_sym_LBRACE] = ACTIONS(259),
    [anon_sym_RBRACE] = ACTIONS(259),
    [anon_sym_SQUOTE] = ACTIONS(259),
    [anon_sym_BQUOTE] = ACTIONS(259),
    [anon_sym_COMMA] = ACTIONS(261),
    [anon_sym_COMMA_AT] = ACTIONS(259),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(259),
    [sym_number] = ACTIONS(261),
    [anon_sym_DQUOTE] = ACTIONS(259),
    [sym_keyword] = ACTIONS(259),
    [sym_boolean] = ACTIONS(259),
    [sym_character] = ACTIONS(259),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [38] = {
    [ts_builtin_sym_end] = ACTIONS(263),
    [sym_symbol] = ACTIONS(265),
    [anon_sym_LPAREN] = ACTIONS(263),
    [anon_sym_RPAREN] = ACTIONS(263),
    [anon_sym_LBRACK] = ACTIONS(263),
    [anon_sym_RBRACK] = ACTIONS(263),
    [anon_sym_LBRACE] = ACTIONS(263),
    [anon_sym_RBRACE] = ACTIONS(263),
    [anon_sym_SQUOTE] = ACTIONS(263),
    [anon_sym_BQUOTE] = ACTIONS(263),
    [anon_sym_COMMA] = ACTIONS(265),
    [anon_sym_COMMA_AT] = ACTIONS(263),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(263),
    [sym_number] = ACTIONS(265),
    [anon_sym_DQUOTE] = ACTIONS(263),
    [sym_keyword] = ACTIONS(263),
    [sym_boolean] = ACTIONS(263),
    [sym_character] = ACTIONS(263),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [39] = {
    [ts_builtin_sym_end] = ACTIONS(267),
    [sym_symbol] = ACTIONS(269),
    [anon_sym_LPAREN] = ACTIONS(267),
    [anon_sym_RPAREN] = ACTIONS(267),
    [anon_sym_LBRACK] = ACTIONS(267),
    [anon_sym_RBRACK] = ACTIONS(267),
    [anon_sym_LBRACE] = ACTIONS(267),
    [anon_sym_RBRACE] = ACTIONS(267),
    [anon_sym_SQUOTE] = ACTIONS(267),
    [anon_sym_BQUOTE] = ACTIONS(267),
    [anon_sym_COMMA] = ACTIONS(269),
    [anon_sym_COMMA_AT] = ACTIONS(267),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(267),
    [sym_number] = ACTIONS(269),
    [anon_sym_DQUOTE] = ACTIONS(267),
    [sym_keyword] = ACTIONS(267),
    [sym_boolean] = ACTIONS(267),
    [sym_character] = ACTIONS(267),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [40] = {
    [ts_builtin_sym_end] = ACTIONS(271),
    [sym_symbol] = ACTIONS(273),
    [anon_sym_LPAREN] = ACTIONS(271),
    [anon_sym_RPAREN] = ACTIONS(271),
    [anon_sym_LBRACK] = ACTIONS(271),
    [anon_sym_RBRACK] = ACTIONS(271),
    [anon_sym_LBRACE] = ACTIONS(271),
    [anon_sym_RBRACE] = ACTIONS(271),
    [anon_sym_SQUOTE] = ACTIONS(271),
    [anon_sym_BQUOTE] = ACTIONS(271),
    [anon_sym_COMMA] = ACTIONS(273),
    [anon_sym_COMMA_AT] = ACTIONS(271),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(271),
    [sym_number] = ACTIONS(273),
    [anon_sym_DQUOTE] = ACTIONS(271),
    [sym_keyword] = ACTIONS(271),
    [sym_boolean] = ACTIONS(271),
    [sym_character] = ACTIONS(271),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [41] = {
    [ts_builtin_sym_end] = ACTIONS(275),
    [sym_symbol] = ACTIONS(277),
    [anon_sym_LPAREN] = ACTIONS(275),
    [anon_sym_RPAREN] = ACTIONS(275),
    [anon_sym_LBRACK] = ACTIONS(275),
    [anon_sym_RBRACK] = ACTIONS(275),
    [anon_sym_LBRACE] = ACTIONS(275),
    [anon_sym_RBRACE] = ACTIONS(275),
    [anon_sym_SQUOTE] = ACTIONS(275),
    [anon_sym_BQUOTE] = ACTIONS(275),
    [anon_sym_COMMA] = ACTIONS(277),
    [anon_sym_COMMA_AT] = ACTIONS(275),
    [anon_sym_POUNDu8_LPAREN] = ACTIONS(275),
    [sym_number] = ACTIONS(277),
    [anon_sym_DQUOTE] = ACTIONS(275),
    [sym_keyword] = ACTIONS(275),
    [sym_boolean] = ACTIONS(275),
    [sym_character] = ACTIONS(275),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(253), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(251), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [25] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(249), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(247), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [50] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(261), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(259), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [75] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(265), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(263), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [100] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(269), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(267), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [125] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(229), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(227), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [150] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(241), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(239), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [175] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(245), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(243), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [200] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(233), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(231), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [225] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(237), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(235), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [250] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(273), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(271), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [275] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(277), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(275), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [300] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(257), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(255), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [325] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(221), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(219), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [350] = 3,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
    ACTIONS(225), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_number,
      sym_symbol,
    ACTIONS(223), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_COMMA_AT,
      anon_sym_POUNDu8_LPAREN,
      anon_sym_DQUOTE,
      sym_keyword,
      sym_boolean,
      sym_character,
  [375] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
    ACTIONS(281), 1,
      aux_sym_string_token1,
    ACTIONS(284), 1,
      sym_escape_sequence,
    ACTIONS(287), 1,
      sym_comment,
    STATE(57), 1,
      aux_sym_string_repeat1,
  [394] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    ACTIONS(291), 1,
      aux_sym_string_token1,
    ACTIONS(293), 1,
      sym_escape_sequence,
    STATE(59), 1,
      aux_sym_string_repeat1,
  [413] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_DQUOTE,
    ACTIONS(297), 1,
      aux_sym_string_token1,
    ACTIONS(299), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym_string_repeat1,
  [432] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(297), 1,
      aux_sym_string_token1,
    ACTIONS(299), 1,
      sym_escape_sequence,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      aux_sym_string_repeat1,
  [451] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
    ACTIONS(305), 1,
      aux_sym_string_token1,
    ACTIONS(307), 1,
      sym_escape_sequence,
    STATE(60), 1,
      aux_sym_string_repeat1,
  [470] = 4,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    ACTIONS(311), 1,
      sym_number,
    STATE(62), 1,
      aux_sym_byte_vector_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [484] = 4,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
    ACTIONS(316), 1,
      sym_number,
    STATE(66), 1,
      aux_sym_byte_vector_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [498] = 4,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    ACTIONS(320), 1,
      sym_number,
    STATE(62), 1,
      aux_sym_byte_vector_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [512] = 4,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    ACTIONS(324), 1,
      sym_number,
    STATE(64), 1,
      aux_sym_byte_vector_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [526] = 4,
    ACTIONS(320), 1,
      sym_number,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_byte_vector_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [540] = 2,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [548] = 2,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
  [556] = 2,
    ACTIONS(332), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(42)] = 0,
  [SMALL_STATE(43)] = 25,
  [SMALL_STATE(44)] = 50,
  [SMALL_STATE(45)] = 75,
  [SMALL_STATE(46)] = 100,
  [SMALL_STATE(47)] = 125,
  [SMALL_STATE(48)] = 150,
  [SMALL_STATE(49)] = 175,
  [SMALL_STATE(50)] = 200,
  [SMALL_STATE(51)] = 225,
  [SMALL_STATE(52)] = 250,
  [SMALL_STATE(53)] = 275,
  [SMALL_STATE(54)] = 300,
  [SMALL_STATE(55)] = 325,
  [SMALL_STATE(56)] = 350,
  [SMALL_STATE(57)] = 375,
  [SMALL_STATE(58)] = 394,
  [SMALL_STATE(59)] = 413,
  [SMALL_STATE(60)] = 432,
  [SMALL_STATE(61)] = 451,
  [SMALL_STATE(62)] = 470,
  [SMALL_STATE(63)] = 484,
  [SMALL_STATE(64)] = 498,
  [SMALL_STATE(65)] = 512,
  [SMALL_STATE(66)] = 526,
  [SMALL_STATE(67)] = 540,
  [SMALL_STATE(68)] = 548,
  [SMALL_STATE(69)] = 556,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_map, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash_map, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_byte_vector, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_byte_vector, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote_splicing, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote_splicing, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_byte_vector, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_byte_vector, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_map, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash_map, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_byte_vector_repeat1, 2, 0, 0),
  [311] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_byte_vector_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_block_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_block_comment] = sym_block_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_block_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sema_external_scanner_create(void);
void tree_sitter_sema_external_scanner_destroy(void *);
bool tree_sitter_sema_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sema_external_scanner_serialize(void *, char *);
void tree_sitter_sema_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sema(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sema_external_scanner_create,
      tree_sitter_sema_external_scanner_destroy,
      tree_sitter_sema_external_scanner_scan,
      tree_sitter_sema_external_scanner_serialize,
      tree_sitter_sema_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
